version: '3'
services:
  nginx:
    image: nginx:stable-alpine # imagen de docker hub que vamos a usar
    container_name: nginx # nombre para referirse al servicio
    restart: unless-stopped
    ports:
      - 9006:80 # puerto de mi pc:puerto del servicio
    volumes:
      - ./:/var/www/html # carpeta local/ vincula a carpeta de nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf # archivo local / reflejado en archivo de la imagen
    depends_on: # para correr este servicio debe estar corriendo php y mysql antes
      - php
      - mysql
    links:
      - php

  php:
    container_name: php
    restart: unless-stopped
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9005:80

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lyo
      MYSQL_USER: lyo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3305:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 9015:80